CREATE TABLE [Minions]
(
	 [Id] INT NOT NULL PRIMARY KEY,
	 [Name] NVARCHAR(20) NOT NULL,
	 [Age] INT NOT NULL
)

CREATE TABLE [Towns]
(
	 [Id] INT NOT NULL PRIMARY KEY,
	 [Name] NVARCHAR(20) NOT NULL,
)