CREATE DATABASE Store

CREATE TABLE ItemTypes(
	ItemTypeID INT IDENTITY NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,

	CONSTRAINT PK_ItemTypes_ItemTypeID
	PRIMARY KEY(ItemTypeID)
)

CREATE TABLE Items(
	ItemID INT IDENTITY NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	ItemTypeID INT NOT NULL

	CONSTRAINT PK_Items_ItemID
	PRIMARY KEY(ItemID),

	CONSTRAINT FK_Items_ItemsType
	FOREIGN KEY(ItemTypeID)
	REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE Cities(
	CityID INT IDENTITY NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,

	CONSTRAINT PK_Cities_CityID
	PRIMARY KEY(CityID)
)

CREATE TABLE Customers(
	CustomerID INT IDENTITY NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	Birthdaty DATE,
	CityID INT NOT NULL,

	CONSTRAINT PK_Customers
	PRIMARY KEY(CustomerID),

	CONSTRAINT FK_Customers_Cities
	FOREIGN KEY(CityID)
	REFERENCES Cities(CityID)
)

CREATE TABLE Orders(
	OrderID INT IDENTITY NOT NULL,
	CustomerID INT NOT NULL,

	CONSTRAINT PK_Orders
	PRIMARY KEY (OrderID),

	CONSTRAINT FK_Orders_Customers
	FOREIGN KEY (CustomerID)
	REFERENCES Customers(CustomerID)
)

CREATE TABLE OrderItems(
	OrderID INT NOT NULL,
	ItemID INT NOT NULL,

	CONSTRAINT PK_OrderItems
	PRIMARY KEY(OrderID, ItemID),

	CONSTRAINT FK_PK_OrderItems_Orders
	FOREIGN KEY(OrderID)
	REFERENCES Orders(OrderID),

	CONSTRAINT FK_PK_OrderItems_Items
	FOREIGN KEY(ItemID)
	REFERENCES Items(ItemID)
)